# Generated by Django 4.1.3 on 2022-11-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tablaPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tablaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacimiento', models.DateField()),
                ('nombre', models.CharField(max_length=155)),
                ('apellido', models.CharField(max_length=155)),
                ('dni', models.IntegerField()),
                ('sueldo_mensual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tablaPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_premio', models.CharField(max_length=200)),
                ('cantidad_nominaciones', models.IntegerField()),
                ('cantidad_premios_ganados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tablaRelaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.tablapelicula')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.tablapersona')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.tablapremio')),
            ],
        ),
    ]
