# Generated by Django 4.1.3 on 2022-11-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablapremio',
            old_name='nombre_premio',
            new_name='premio_ganador',
        ),
    ]
