# Generated by Django 4.1.3 on 2022-12-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_tablarelacione'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablapelicula',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peliculas.tablapersona'),
        ),
        migrations.AddField(
            model_name='tablapremio',
            name='pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peliculas.tablapelicula'),
        ),
        migrations.DeleteModel(
            name='tablaRelacione',
        ),
    ]
