# Generated by Django 4.1.3 on 2022-12-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_remove_tablapremio_cantidad_premios_ganados'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablapelicula',
            name='clob',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
