# Generated by Django 4.1.3 on 2022-12-14 16:28

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_tablapelicula_clob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablapelicula',
            name='clob',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
    ]
