# Generated by Django 4.1.3 on 2022-12-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0010_tablapelicula_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablapremio',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
