# Generated by Django 4.1.3 on 2022-12-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0013_tablapremio_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablapremio',
            name='base',
            field=models.CharField(blank=True, max_length=20000000, null=True),
        ),
    ]
