# Generated by Django 4.1.3 on 2023-01-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0014_alter_tablapremio_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablaImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='fotos')),
            ],
        ),
    ]
