# Generated by Django 4.1.3 on 2023-01-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0015_tablaimagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaimagenes',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='tablapremio',
            name='base',
        ),
        migrations.AddField(
            model_name='tablaimagenes',
            name='base',
            field=models.CharField(blank=True, max_length=20000000, null=True),
        ),
    ]
