# Generated by Django 4.1.3 on 2023-01-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0017_remove_tablapelicula_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablapremio',
            name='premio_ganador',
        ),
    ]
