# Generated by Django 4.1.3 on 2023-01-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0018_remove_tablapremio_premio_ganador'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablaCines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('direccion', models.CharField(max_length=400)),
                ('posicion_gps', models.CharField(max_length=400)),
                ('telefono', models.PositiveIntegerField()),
                ('web', models.CharField(max_length=400)),
            ],
        ),
    ]
