# Generated by Django 4.1.3 on 2023-01-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0020_alter_tablacines_posicion_gps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablacines',
            name='posicion_gps',
        ),
        migrations.AddField(
            model_name='tablacines',
            name='latitud',
            field=models.CharField(default='122', max_length=400),
        ),
        migrations.AddField(
            model_name='tablacines',
            name='longitud',
            field=models.CharField(default='122', max_length=400),
        ),
    ]
