# Generated by Django 4.1.3 on 2023-01-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0021_remove_tablacines_posicion_gps_tablacines_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablapersona',
            name='sueldo_mensual',
            field=models.FloatField(),
        ),
    ]
